//-----------------------------------------------------------------------------
// Copyright 2015 Thiago Alves
// This file is part of the OpenPLC Software Stack.
//
// OpenPLC is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// OpenPLC is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with OpenPLC.  If not, see <http://www.gnu.org/licenses/>.
//------
//
// This file is responsible for gluing the variables from the IEC program to
// the OpenPLC memory pointers. It is automatically generated by the
// glue_generator program. PLEASE DON'T EDIT THIS FILE!
// Thiago Alves, May 2016
//-----------------------------------------------------------------------------

#include "iec_std_lib.h"

TIME __CURRENT_TIME;
extern unsigned long long common_ticktime__;

#define BUFFER_SIZE		1024

//Internal buffers for I/O and memory. These buffers are defined in the
//main program

//Booleans
static IEC_BOOL *(*bool_input_ptr)[8] = NULL;
static IEC_BOOL *(*bool_output_ptr)[8] = NULL;

//Bytes
static IEC_BYTE *(*byte_input_ptr)[8] = NULL;
static IEC_BYTE *(*byte_output_ptr)[8] = NULL;

//Analog I/O
static IEC_UINT *(*int_input_ptr)[8] = NULL;
static IEC_UINT *(*int_output_ptr)[8] = NULL;

//32bit I/O
static IEC_UDINT *(*dint_input_ptr)[8] = NULL;
static IEC_UDINT *(*dint_output_ptr)[8] = NULL;

//64bit I/O
static IEC_ULINT *(*lint_input_ptr)[8] = NULL;
static IEC_ULINT *(*lint_output_ptr)[8] = NULL;

//Memory
static IEC_UINT *(*int_memory_ptr)[8] = NULL;
static IEC_UDINT *(*dint_memory_ptr)[8] = NULL;
static IEC_ULINT *(*lint_memory_ptr)[8] = NULL;

//Special Functions
static IEC_ULINT *special_functions[BUFFER_SIZE];


#define __LOCATED_VAR(type, name, ...) type __##name;
#include "LOCATED_VARIABLES.h"
#undef __LOCATED_VAR
#define __LOCATED_VAR(type, name, ...) type* name = &__##name;
#include "LOCATED_VARIABLES.h"
#undef __LOCATED_VAR

void setBufferPointers(IEC_BOOL *input_bool[BUFFER_SIZE][8], IEC_BOOL *output_bool[BUFFER_SIZE][8],
						IEC_BYTE *input_byte[BUFFER_SIZE][8], IEC_BYTE *output_byte[BUFFER_SIZE][8],
						IEC_UINT *input_int[BUFFER_SIZE][8], IEC_UINT *output_int[BUFFER_SIZE][8],
						IEC_UDINT *input_dint[BUFFER_SIZE][8], IEC_UDINT *output_dint[BUFFER_SIZE][8],
						IEC_ULINT *input_lint[BUFFER_SIZE][8], IEC_ULINT *output_lint[BUFFER_SIZE][8],
						IEC_UINT *int_memory[BUFFER_SIZE][8], IEC_UDINT *dint_memory[BUFFER_SIZE][8], IEC_ULINT *lint_memory[BUFFER_SIZE][8])
{
	bool_input_ptr = input_bool;
	bool_output_ptr = output_bool;
	byte_input_ptr = input_byte;
	byte_output_ptr = output_byte;
	int_input_ptr = input_int;
	int_output_ptr = output_int;
	dint_input_ptr = input_dint;
	dint_output_ptr = output_dint;
	lint_input_ptr = input_lint;
	lint_output_ptr = output_lint;
	int_memory_ptr = int_memory;
	dint_memory_ptr = dint_memory;
	lint_memory_ptr = lint_memory;
}

void glueVars()
{
	bool_output_ptr[0][0] = (IEC_BOOL *)__QX0_0;
}

void updateTime()
{
	__CURRENT_TIME.tv_sec  += common_ticktime__ / 1000000000ULL;
	__CURRENT_TIME.tv_nsec += common_ticktime__ % 1000000000ULL;

	if (__CURRENT_TIME.tv_nsec >= 1000000000ULL)
	{
		__CURRENT_TIME.tv_nsec -= 1000000000ULL;
		__CURRENT_TIME.tv_sec += 1;
	}
}